### ISSUE TITLE
[Bug] 无法选择语言模型

### ISSUE THREAD

**Issue by yincangshiwei** [lobehub/lobe-vidol#102]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

点击模型那里，选择其它模型后没反应，还是默认的gpt3.5
![image](https://github.com/lobehub/lobe-vidol/assets/8185843/a4000bc9-4392-4e1f-a19a-5788aa8296cc)

### 🚦 期望结果 | Expected Behavior

能成功选择其它模型。

**Comment by rdmclin2** [comment]
@MarioJames 看下这个问题

**Comment by MarioJames** [comment]
我排查下 刚休假回来

**Comment by MarioJames** [comment]
@yincangshiwei 我这边没能复现这个问题 能否给个复现路径或者给个控制台截图呢

**Comment by rdmclin2** [comment]
fixed
