### ISSUE TITLE
[Request] model.vrm无法加载，显示跨域限制

### ISSUE THREAD

**Issue by gavid0124** [lobehub/lobe-vidol#136]
### 🥰 需求描述 | Feature Description

希望model.vrm和xxx.fbx文件从本地加载

### 🧐 解决方案 | Proposed Solution

希望model.vrm和xxx.fbx文件从本地加载

### 📝 补充信息 | Additional Information

这是报错信息：
Access to fetch at 'https://r2.vidol.chat/agents/vidol-agent-sample-a/model.vrm' from origin 'http://xxx:xxx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by rdmclin2** [comment]
是私有化部署？oss 现在做了防刷限制，非 vidol.chat 的域名不能加载，需要自己做 market

**Comment by gavid0124** [comment]
> 是私有化部署？oss 现在做了防刷限制，非 vidol.chat 的域名不能加载，需要自己做 market

好的，明白了。

**Comment by rdmclin2** [comment]
@gavid0124 现在放开 oss 的限制了，R2 读取很便宜
