### ISSUE TITLE
[Question] “你可以使用vmd文件和你最喜欢的偶像一起跳舞”，没找到对应的界面

### ISSUE THREAD

**Issue by gavid0124** [lobehub/lobe-vidol#138]
### 🧐 问题描述 | Proposed Solution

“MMD Dance 支持
借助 mmd-parser 的支持，你可以使用vmd文件和你最喜欢的偶像一起跳舞; Just Dance!”，没找到下面这个界面，截图如下：
<img width="1455" alt="324901875-8d1107c7-bec9-4f20-a8ac-1413d3682587" src="https://github.com/user-attachments/assets/3a39b363-ad14-436b-98a8-98246e58b7c6">

**Comment by rdmclin2** [comment]
直接拖 vmd 文件到模型上就可以，不过这种方式是没有音乐的

**Comment by gavid0124** [comment]
> @gavid0124 直接拖 vmd 文件到模型上就可以，不过这种方式是没有音乐的

好的，明白了，感谢您。

**Comment by rdmclin2** [comment]
![image](https://github.com/user-attachments/assets/c6538879-43ba-420a-b4d0-4f60c7e420ba)

@gavid0124 舞蹈上传功能已经上线，现在你可以上传自己的 VMD 文件到平台上了。
