### ISSUE TITLE
[Question] 代码中加载的模型配置清单json url地址不存在了

### ISSUE THREAD

**Issue by dcdlove** [lobehub/lobe-vidol#154]
### 🧐 问题描述 | Proposed Solution

不知道结构是什么样的
export const AGENT_INDEX_URL = 'https://market.vidol.chat/agents/index.json';

export const DANCE_INDEX_URL = 'https://market.vidol.chat/dances/index.json';

### 📝 补充信息 | Additional Information

export const AGENT_INDEX_URL = 'https://market.vidol.chat/agents/index.json';

export const DANCE_INDEX_URL = 'https://market.vidol.chat/dances/index.json';

**Comment by dcdlove** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by rdmclin2** [comment]
迁移到这里了： 

export const AGENT_INDEX_URL = 'https://vidol-market.lobehub.com/agents/index.json';

export const DANCE_INDEX_URL = 'https://vidol-market.lobehub.com/dances/index.json';
