### ISSUE TITLE
[Request] custom model name

### ISSUE THREAD

**Issue by StudyingLover** [lobehub/lobe-vidol#164]
### 🥰 需求描述 | Feature Description

for example, I want use [Deepseek](https://www.deepseek.com/), I have base url and api key
 but I can't use deepseek because I only use chatgpt on this [web](https://vidol.lobehub.com/)

### 🧐 解决方案 | Proposed Solution

Provide the user with an input box where they can enter the model name themselves.

**Comment by rdmclin2** [comment]
ok，我周末加下这个功能

**Comment by rdmclin2** [comment]
@StudyingLover  We have supported multiple llm providers , you can try it on https://vidol.lobehub.com/
![feat-multi-ai-provider](https://github.com/user-attachments/assets/87f72a2d-2142-414d-a34c-c1db42865c94)
