### ISSUE TITLE
[Request] Allow us to use local language models like Florence-2

### ISSUE THREAD

**Issue by SomeNiceDude** [lobehub/lobe-vidol#166]
### 🥰 需求描述 | Feature Description

Right now only OpenAI Models are available, which have a limited quota. 

### 🧐 解决方案 | Proposed Solution

Allowing us to use Florence-2 will get rid of this limitation and allow us to generate an unlimited amount of conversations for free.

**Comment by rdmclin2** [comment]
@SomeNiceDude We have supported multiple llm providers , you can try it on https://vidol.lobehub.com/
![feat-multi-ai-provider](https://github.com/user-attachments/assets/87f72a2d-2142-414d-a34c-c1db42865c94)
