### ISSUE TITLE
[Bug] ai对话失败

### ISSUE THREAD

**Issue by 239573049** [lobehub/lobe-vidol#33]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-vidol/assets/61819790/b98a28e5-72d3-4480-8ddd-89b924bd70a8)
我使用的是代理直接代理到openai的
![image](https://github.com/lobehub/lobe-vidol/assets/61819790/6e13caa6-2cb5-4c21-9e0f-0e54a8b2aebf)
我发现请求的时候会携带多余字段导致失败。

**Comment by rdmclin2** [comment]
收到，之前都是用的国内的代理，没有测试直连 openai 的情况，我看如何修复下。

**Comment by rdmclin2** [comment]
![image](https://github.com/lobehub/lobe-vidol/assets/4705237/061e5cf0-5a55-43bf-81df-10dd3840d73c)

cc @239573049 再试下
