### ISSUE TITLE
"角色“页面显示[Bug] 

### ISSUE THREAD

**Issue by snape4669** [lobehub/lobe-vidol#52]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

点击“角色”页面后出现错误，错误信息：Application error: a client-side exception has occurred (see the browser console for more information).
![image](https://github.com/lobehub/lobe-vidol/assets/125938027/12954cf0-2e84-4c11-b38d-e9489fdecf07)

### 🚦 期望结果 | Expected Behavior

修复

**Comment by snape4669** [comment]
版本号：0.6.0

**Comment by rdmclin2** [comment]
@snape4669  收到，从报错看是控制 panel 显隐的变量未读取到，不确定什么原因导致，这边暂时没有复现，可以试下在系统设置中重置系统设置，项目在前期施工中造成的不便敬请谅解。

**Comment by snape4669** [comment]
@rdmclin2 收到，经重置系统设置后，问题解决，但无法知道是否和前期设置相关
